#include "model/Scooby-van.hpp"

#include "model/Primitives.hpp"

#include <rlgl.h>

// =====================================================================================
//  Scooby-Doo "Mystery Machine" van.
//
//  GENERATED by `scooby-do-the-mystery-machine_zip/gen2.py` straight from the Blockbench
//  glTF (`source/scooby_do.gltf`). Do not hand-edit the data tables; re-run the generator.
//
//  The glTF body is 129 textured cuboids ("cube" mesh nodes), many rotated about X to
//  fake the rounded van shell, in three bones: the main `bone`, plus the two front
//  sub-assemblies `bone2` (left) and `dwerka` (right). Each cuboid is baked below as a
//  Part = {world centre, local size, axis-angle rotation, flat material colour}; the
//  colour is sampled from the original atlas so the materials match without ever binding
//  the atlas at runtime. Every Part is drawn through the `drawBox` building block wrapped
//  in real rlgl matrix ops (translate + rotate), preserving the source hierarchy.
//
//  The glTF's 97 "octagon" prisms (which faked the 4 wheels and 2 headlights) are NOT
//  baked: per the assignment they are rebuilt as real cylinders (drawWheel / drawLight),
//  placed with matrix ops, plus one nose-mounted spare wheel. Measurements come from the
//  octagon clusters: wheels x=+/-0.80, y=-0.91, front z=-0.95 / rear z=+0.98, r=0.41,
//  width(X)=0.37; headlights front face z=-1.95, x=+/-0.28, y=-0.19, r=0.17.
//
//  Everything is in the centroid-recentred frame (glTF centroid (0,1.2365,0.089) -> the
//  origin) so the trackball viewer spins about the model centre with no extra offset.
//
//  Only the left/right side panels are textured, with the real MysteryMachineBottomDecal
//  (the flame stripe), embedded as base64 -- the single texture the brief asks for.
// =====================================================================================

namespace raylibgl::model {

    namespace {

        // One baked Blockbench cuboid: centre + size in the recentred frame, an axis-angle
        // rotation (degrees), and a flat material colour sampled from the original atlas.
        struct Part {
            float center[3];
            float size[3];
            float axisAngle[4];  // {ax, ay, az, degrees}
            unsigned char color[4];
        };

        const Part BODY_PARTS[] = {
            {{0.0,-0.8673,-1.564}, {2.0,0.125,0.375}, {1.0,0.0,0.0,0.0}, {105,29,7,255}},
            {{0.0,-0.08434,-1.851}, {2.0,0.125,0.375}, {-1.0,0.0,0.0,85.0}, {184,17,23,255}},
            {{0.9375,0.5225,-1.61}, {0.125,0.125,1.0}, {-1.0,0.0,0.0,62.5}, {17,183,184,255}},
            {{-0.9375,-0.4231,1.963}, {0.125,1.0,0.125}, {1.0,0.0,0.0,10.0}, {15,9,34,255}},
            {{-0.9375,0.5363,1.871}, {0.125,1.062,0.125}, {-1.0,0.0,0.0,20.0}, {24,32,39,255}},
            {{0.0,1.118,0.1836}, {2.0,0.125,2.062}, {-1.0,0.0,0.0,2.5}, {17,183,184,255}},
            {{0.0,1.007,-1.116}, {2.0,0.125,0.625}, {-1.0,0.0,0.0,13.5}, {17,183,184,255}},
            {{-9.628e-17,-0.799,1.973}, {2.125,0.375,0.25}, {6.123e-17,1.0,6.123e-17,180.0}, {198,216,216,255}},
            {{-0.9376,0.5225,-1.61}, {0.125,0.125,1.0}, {-1.0,0.0,0.0,62.5}, {91,188,244,255}},
            {{0.0,1.081,1.461}, {2.0,0.5625,0.125}, {-1.0,0.0,0.0,72.5}, {17,183,184,255}},
            {{-0.7187,-0.5803,-1.402}, {0.5625,0.5625,0.125}, {1.0,0.0,0.0,7.5}, {17,183,184,255}},
            {{-0.7187,-0.6115,-0.5265}, {0.5625,0.625,0.125}, {-1.0,0.0,0.0,17.5}, {17,183,184,255}},
            {{-0.7188,-0.6115,1.411}, {0.5625,0.625,0.125}, {-1.0,0.0,0.0,20.0}, {17,183,184,255}},
            {{-0.7811,-0.3615,0.9735}, {0.4375,0.125,0.75}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.9375,-0.4231,1.963}, {0.125,1.0,0.125}, {1.0,0.0,0.0,10.0}, {33,43,52,255}},
            {{0.0,-0.6693,1.919}, {1.75,0.5,0.125}, {1.0,0.0,0.0,10.0}, {17,183,184,255}},
            {{0.9375,0.5363,1.871}, {0.125,1.062,0.125}, {-1.0,0.0,0.0,20.0}, {148,54,43,255}},
            {{-0.4361,0.5363,1.871}, {0.875,1.063,0.125}, {-1.0,0.0,0.0,20.0}, {24,32,39,255}},
            {{0.4389,0.5363,1.871}, {0.875,1.063,0.125}, {-1.0,0.0,0.0,20.0}, {17,183,184,255}},
            {{-0.4361,-0.1768,2.006}, {0.875,0.5,0.125}, {1.0,0.0,0.0,10.0}, {17,183,184,255}},
            {{0.4389,-0.1768,2.006}, {0.875,0.5,0.125}, {1.0,0.0,0.0,10.0}, {20,27,33,255}},
            {{-0.5,-0.7365,0.9579}, {0.125,0.375,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.5,-0.7677,0.9735}, {0.125,0.3125,1.0}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.03125,-0.8615,0.9735}, {0.9375,0.125,1.0}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.03125,-0.8615,-0.9328}, {1.062,0.125,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.4688,-0.7052,-0.9328}, {0.0625,0.1875,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.5,-0.4552,0.9735}, {0.125,0.3125,0.75}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.5,-0.424,0.9735}, {0.125,0.25,0.75}, {1.0,0.0,0.0,0.0}, {0,119,120,255}},
            {{-0.4688,-0.4552,-0.9953}, {0.0625,0.3125,0.8125}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.5312,-0.4552,-0.9953}, {0.0625,0.3125,0.8125}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.5312,-0.7052,-0.9328}, {0.0625,0.1875,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.7188,-0.4026,-1.845}, {0.1875,0.1875,0.125}, {-1.0,0.0,0.0,15.0}, {69,0,0,255}},
            {{0.7188,-0.2899,-1.907}, {0.3125,0.0625,0.1875}, {-1.0,0.0,0.0,15.0}, {234,237,112,255}},
            {{0.8438,-0.4489,-1.897}, {0.0625,0.25,0.125}, {-1.0,0.0,0.0,15.0}, {17,183,184,255}},
            {{0.6875,-0.5395,-1.873}, {0.25,0.0625,0.125}, {-1.0,0.0,0.0,15.0}, {9,146,154,255}},
            {{0.5938,-0.4187,-1.905}, {0.0625,0.1875,0.125}, {-1.0,0.0,0.0,15.0}, {26,208,200,255}},
            {{0.7188,-0.6827,-1.836}, {0.1875,0.125,0.125}, {-1.0,0.0,0.0,15.0}, {0,119,120,255}},
            {{-0.7188,-0.6827,-1.836}, {0.1875,0.125,0.125}, {-1.0,0.0,0.0,15.0}, {248,221,114,255}},
            {{-0.7188,-0.4026,-1.845}, {0.1875,0.1875,0.125}, {-1.0,0.0,0.0,15.0}, {234,237,112,255}},
            {{-0.8438,-0.4187,-1.905}, {0.0625,0.1875,0.125}, {-1.0,0.0,0.0,15.0}, {15,9,34,255}},
            {{-0.5938,-0.4489,-1.897}, {0.0625,0.25,0.125}, {-1.0,0.0,0.0,15.0}, {67,232,141,255}},
            {{-0.75,-0.5395,-1.873}, {0.25,0.0625,0.125}, {-1.0,0.0,0.0,15.0}, {198,216,216,255}},
            {{-0.7188,-0.2899,-1.907}, {0.3125,0.0625,0.1875}, {-1.0,0.0,0.0,15.0}, {26,208,200,255}},
            {{-0.75,-0.3615,-0.964}, {0.5,0.125,0.75}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.9343,-0.4879,-1.45}, {0.125,0.625,0.0625}, {1.0,0.0,0.0,7.5}, {17,183,184,255}},
            {{-0.9374,0.4059,0.9886}, {0.125,1.438,0.75}, {1.0,0.0,0.0,0.0}, {33,43,52,255}},
            {{-0.9374,0.2497,1.395}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9374,0.09344,1.614}, {0.125,1.938,0.25}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.9374,0.1872,1.457}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{-0.9374,-0.0003125,1.77}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{-0.9374,-0.09406,1.832}, {0.125,1.562,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9374,-0.03156,1.895}, {0.125,1.188,0.0625}, {1.0,0.0,0.0,0.0}, {69,0,0,255}},
            {{-0.9374,-0.0003125,1.957}, {0.125,0.625,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9371,0.2184,-0.5426}, {0.125,1.812,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9374,1.013,-0.6899}, {0.125,0.125,0.25}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.9374,1.013,-0.9711}, {0.125,0.125,0.3125}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.0,0.4889,-1.666}, {1.75,6.258e-05,1.0}, {-1.0,0.0,0.0,62.5}, {91,188,244,255}},
            {{-6.229e-06,-0.5815,-1.78}, {2.0,0.6875,0.125}, {-1.0,0.0,0.0,15.0}, {17,183,184,255}},
            {{0.0,-0.2053,-0.9015}, {1.625,0.1875,1.0}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.0,0.2097,-0.407}, {1.625,0.1875,1.0}, {1.0,0.0,0.0,100.0}, {17,183,184,255}},
            {{0.0,0.2097,0.7805}, {1.625,0.1875,1.0}, {1.0,0.0,0.0,100.0}, {148,54,43,255}},
            {{0.0,-0.2053,0.3485}, {1.625,0.1875,0.875}, {1.0,0.0,0.0,0.0}, {180,212,225,255}},
            {{0.0,-0.549,1.411}, {0.875,0.5,0.125}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{0.03125,-0.549,-0.964}, {0.9375,0.5,1.0}, {1.0,0.0,0.0,0.0}, {33,43,52,255}},
            {{0.0,-0.549,0.1922}, {1.625,0.5,0.5625}, {1.0,0.0,0.0,0.0}, {0,119,120,255}},
            {{-0.8438,-0.1115,1.067}, {0.0625,0.375,0.5625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.0,-0.8615,1.692}, {2.0,0.125,0.4375}, {1.0,0.0,0.0,0.0}, {69,0,0,255}},
            {{0.0,-0.8673,-1.564}, {2.0,0.125,0.375}, {1.0,0.0,0.0,0.0}, {105,29,7,255}},
            {{0.0,-0.799,-1.777}, {2.125,0.375,0.25}, {1.0,0.0,0.0,0.0}, {20,27,33,255}},
            {{-0.02653,-0.3409,-1.732}, {1.875,1.0,0.1875}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.536,0.002802,-1.607}, {0.75,0.3125,0.0625}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{-0.7187,-0.6115,0.536}, {0.5625,0.625,0.125}, {1.0,0.0,0.0,20.0}, {17,183,184,255}},
            {{-0.9374,0.2809,0.5511}, {0.125,1.688,0.125}, {1.0,0.0,0.0,0.0}, {255,248,153,255}},
            {{-0.9373,0.1559,-0.01137}, {0.125,1.938,1.0}, {1.0,0.0,0.0,0.0}, {0,119,120,255}},
            {{0.8438,-0.1115,1.067}, {0.0625,0.375,0.5625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.7187,-0.6115,-0.5265}, {0.5625,0.625,0.125}, {-1.0,0.0,0.0,17.5}, {17,183,184,255}},
            {{0.75,-0.3615,-0.964}, {0.5,0.125,0.75}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.9373,0.1559,-0.01137}, {0.125,1.938,1.0}, {1.0,0.0,0.0,0.0}, {189,74,39,255}},
            {{0.9374,0.4059,0.9886}, {0.125,1.438,0.75}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.9374,0.2809,0.5511}, {0.125,1.688,0.125}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{0.9374,0.09344,1.614}, {0.125,1.938,0.25}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.9374,-0.0003125,1.957}, {0.125,0.625,0.0625}, {1.0,0.0,0.0,0.0}, {10,154,169,255}},
            {{0.9374,-0.03156,1.895}, {0.125,1.188,0.0625}, {1.0,0.0,0.0,0.0}, {83,97,116,255}},
            {{0.9374,-0.09406,1.832}, {0.125,1.562,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.9374,-0.0003125,1.77}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.9374,0.1872,1.457}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.9374,0.2497,1.395}, {0.125,1.75,0.0625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.7187,-0.6115,0.536}, {0.5625,0.625,0.125}, {1.0,0.0,0.0,20.0}, {17,183,184,255}},
            {{0.7811,-0.3615,0.9735}, {0.4375,0.125,0.75}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.7188,-0.6115,1.411}, {0.5625,0.625,0.125}, {-1.0,0.0,0.0,20.0}, {17,183,184,255}},
            {{0.9374,1.013,-0.9711}, {0.125,0.125,0.3125}, {1.0,0.0,0.0,0.0}, {234,237,112,255}},
            {{0.9374,1.013,-0.6899}, {0.125,0.125,0.25}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{0.9371,0.2184,-0.5426}, {0.125,1.812,0.0625}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.0,1.198,-0.2869}, {2.0,0.125,0.125}, {1.0,0.0,0.0,0.0}, {110,120,140,255}},
            {{0.0,1.261,1.026}, {2.0,0.125,0.125}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{0.0,-0.8615,0.00475}, {2.0,0.125,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.964,0.5028,-1.138}, {6.247e-05,0.8125,0.875}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{0.03125,-0.7178,2.111}, {0.8125,0.1875,6.247e-05}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.03125,-0.7178,-1.914}, {0.8125,0.1875,6.247e-05}, {1.0,0.0,0.0,0.0}, {24,32,39,255}},
            {{0.7187,-0.5803,-1.402}, {0.5625,0.5625,0.125}, {1.0,0.0,0.0,7.5}, {17,183,184,255}},
        };

        const Part HUB_L_PARTS[] = {
            {{-1.18,0.08599,-1.607}, {0.25,0.3125,0.0625}, {1.0,0.0,0.0,0.0}, {20,27,33,255}},
            {{-1.024,0.1485,-1.607}, {0.0625,0.0625,0.0625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-1.024,0.02349,-1.607}, {0.0625,0.0625,0.0625}, {1.0,0.0,0.0,0.0}, {105,29,7,255}},
            {{-0.9999,-0.01775,-1.127}, {6.253e-05,0.3125,0.875}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9374,0.4786,-1.49}, {0.125,0.125,1.0}, {-1.0,0.0,0.0,62.5}, {148,54,43,255}},
            {{-0.9374,0.8885,-1.002}, {0.125,0.625,0.125}, {-1.0,0.0,0.0,90.0}, {148,54,43,255}},
            {{-0.9374,0.326,-0.6274}, {0.125,1.25,0.125}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{-0.9374,-0.2365,-1.065}, {0.125,0.125,0.75}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.9999,-0.4865,-1.534}, {6.253e-05,0.625,0.0625}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{-0.9999,-0.424,-1.471}, {6.253e-05,0.5,0.0625}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{-0.9999,-0.2678,-1.627}, {6.253e-05,0.8125,0.125}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{-0.9375,-0.533,-1.663}, {0.125,0.625,0.125}, {-1.0,0.0,0.0,15.0}, {10,154,169,255}},
            {{-0.9374,-0.09711,-1.728}, {0.125,0.125,0.3125}, {-1.0,0.0,0.0,85.0}, {26,208,200,255}},
            {{-0.9374,0.076,-1.159}, {0.125,0.125,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
        };

        const Part HUB_R_PARTS[] = {
            {{0.9374,0.4786,-1.49}, {0.125,0.125,1.0}, {-1.0,0.0,0.0,62.5}, {38,25,67,255}},
            {{0.9374,0.8885,-1.002}, {0.125,0.625,0.125}, {-1.0,0.0,0.0,90.0}, {0,101,102,255}},
            {{0.9374,0.326,-0.6274}, {0.125,1.25,0.125}, {1.0,0.0,0.0,0.0}, {148,54,43,255}},
            {{0.9735,0.5028,-1.138}, {6.247e-05,0.8125,0.875}, {1.0,0.0,0.0,0.0}, {198,216,216,255}},
            {{1.0,-0.01775,-1.127}, {6.247e-05,0.3125,0.875}, {1.0,0.0,0.0,0.0}, {39,200,201,255}},
            {{0.9374,-0.2365,-1.065}, {0.125,0.125,0.75}, {1.0,0.0,0.0,0.0}, {234,237,112,255}},
            {{1.0,-0.424,-1.471}, {6.247e-05,0.5,0.0625}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
            {{1.0,-0.2678,-1.627}, {6.247e-05,0.8125,0.125}, {1.0,0.0,0.0,0.0}, {0,119,120,255}},
            {{1.0,-0.4865,-1.534}, {6.247e-05,0.625,0.0625}, {1.0,0.0,0.0,0.0}, {10,154,169,255}},
            {{0.9374,-0.09711,-1.728}, {0.125,0.125,0.3125}, {-1.0,0.0,0.0,85.0}, {248,221,114,255}},
            {{0.9375,-0.533,-1.663}, {0.125,0.625,0.125}, {-1.0,0.0,0.0,15.0}, {17,183,184,255}},
            {{1.024,0.1485,-1.607}, {0.0625,0.0625,0.0625}, {1.0,0.0,0.0,0.0}, {38,25,67,255}},
            {{1.024,0.02349,-1.607}, {0.0625,0.0625,0.0625}, {1.0,0.0,0.0,0.0}, {38,25,67,255}},
            {{1.18,0.08599,-1.607}, {0.25,0.3125,0.0625}, {1.0,0.0,0.0,0.0}, {105,29,7,255}},
            {{0.9374,0.076,-1.159}, {0.125,0.125,0.9375}, {1.0,0.0,0.0,0.0}, {17,183,184,255}},
        };

        // ---- Round parts: measured from the octagon clusters (recentred frame) --------
        constexpr float WHEEL_X = 0.80f;
        constexpr float WHEEL_Y = -0.91f;
        constexpr float FRONT_AXLE_Z = -0.95f;
        constexpr float REAR_AXLE_Z = 0.98f;
        constexpr float TIRE_RADIUS = 0.41f;
        constexpr float TIRE_WIDTH = 0.37f;
        constexpr int WHEEL_SIDES = 14;

        constexpr float LIGHT_X = 0.28f;
        constexpr float LIGHT_Y = -0.19f;
        constexpr float LIGHT_Z = -1.95f;
        constexpr float LIGHT_RADIUS = 0.17f;
        constexpr float LIGHT_DEPTH = 0.16f;
        constexpr int LIGHT_SIDES = 12;

        constexpr float SPARE_RADIUS = 0.38f;
        constexpr float SPARE_DEPTH = 0.16f;
        constexpr int SPARE_SIDES = 14;

        constexpr Color RUBBER_BLACK = Color{24, 29, 35, 255};
        constexpr Color HUBCAP_BLUE = Color{88, 190, 224, 255};
        constexpr Color LIGHT_YELLOW = Color{247, 225, 111, 255};

        // ---- Side decal (MysteryMachineBottomDecal.png), embedded as base64 ------------
        const char SIDE_DECAL_PNG_B64[] =
            "iVBORw0KGgoAAAANSUhEUgAAACAAAAAMBAMAAADxOqKKAAAAAXNSR0IArs4c6QAAAARnQU1BAACx"
            "jwv8YQUAAAAhUExURRG3uBrQyABlZgB3eOrtcL1KJ8lSK9ZbL+/2mrgRF9AaHHuLahQAAAAJcEhZ"
            "cwAADsMAAA7DAcdvqGQAAACWSURBVBjTVYvREYIwEESPpAFKYNACMiZDAWbRBkAKQIMFGI4K9Fqg"
            "Bas0xPHDnbvdeztzVJSUVJS/TKbsodpA7WxOcmjHLZsOPhd7DJMh0nPEMRcKE4/WNjxjezG1cacQ"
            "L7chXL2uNVXaQ54cAt8FzijyxsmLsxbx2hE8AjPyBDgQkK7H+bsJSETaDrHvB7RdAlrff1o/Quw1"
            "MlAKa3MAAAAASUVORK5CYII=";

        constexpr float DECAL_X = 1.075f;  // just outside the body shell (cube bbox x ~ 1.06)

        Texture2D g_sideDecal{};
        bool g_resourcesLoaded = false;

        void ensureResourcesLoaded() {
            if (g_resourcesLoaded) {
                return;
            }
            int size = 0;
            unsigned char* png = DecodeDataBase64(SIDE_DECAL_PNG_B64, &size);
            Image image = LoadImageFromMemory(".png", png, size);
            MemFree(png);
            g_sideDecal = LoadTextureFromImage(image);
            SetTextureFilter(g_sideDecal, TEXTURE_FILTER_POINT);
            UnloadImage(image);
            g_resourcesLoaded = true;
        }

        // Draw a baked group of cuboids: each placed with its own translate + rotate, then
        // emitted by the drawBox building block in its flat material colour.
        void drawParts(const Part* parts, int count, bool wire) {
            for (int i = 0; i < count; ++i) {
                const Part& p = parts[i];
                rlPushMatrix();
                rlTranslatef(p.center[0], p.center[1], p.center[2]);
                if (p.axisAngle[3] != 0.0f) {
                    rlRotatef(p.axisAngle[3], p.axisAngle[0], p.axisAngle[1], p.axisAngle[2]);
                }
                drawBox(Vector3{0.0f, 0.0f, 0.0f}, Vector3{p.size[0], p.size[1], p.size[2]},
                        Color{p.color[0], p.color[1], p.color[2], p.color[3]}, wire);
                rlPopMatrix();
            }
        }

        template<int N>
        void drawParts(const Part (&parts)[N], bool wire) {
            drawParts(parts, N, wire);
        }

        // Place the four road wheels with matrix transforms; geometry from drawWheel.
        void drawWheels(bool wire) {
            const float z[] = {FRONT_AXLE_Z, REAR_AXLE_Z};
            for (int sx = -1; sx <= 1; sx += 2) {
                for (float wz: z) {
                    rlPushMatrix();
                    rlTranslatef(sx * WHEEL_X, WHEEL_Y, wz);
                    drawWheel(wire);
                    rlPopMatrix();
                }
            }
        }

        // Place the two headlights with matrix transforms; geometry from drawLight.
        void drawHeadlights(bool wire) {
            for (int sx = -1; sx <= 1; sx += 2) {
                rlPushMatrix();
                rlTranslatef(sx * LIGHT_X, LIGHT_Y, LIGHT_Z);
                drawLight(wire);
                rlPopMatrix();
            }
        }

        // The single nose-mounted spare wheel (cylinder, axle along Z, facing forward).
        void drawSpareWheel(bool wire) {
            rlPushMatrix();
            rlTranslatef(0.0f, 0.10f, -1.97f);
            rlRotatef(90.0f, 1.0f, 0.0f, 0.0f);  // cylinder +Y axis -> +Z
            drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, SPARE_RADIUS, SPARE_DEPTH, RUBBER_BLACK, wire, SPARE_SIDES);
            drawCylinder(Vector3{0.0f, -SPARE_DEPTH * 0.5f - 0.01f, 0.0f}, SPARE_RADIUS * 0.5f, 0.04f, HUBCAP_BLUE, wire,
                         SPARE_SIDES);
            rlPopMatrix();
        }

        // Left/right flame decal: the only textured geometry, mirrored across the two sides.
        void drawSideDecal(int sx, bool wire) {
            const float x = sx * DECAL_X;
            const float y0 = -0.62f, y1 = 0.34f, z0 = -1.45f, z1 = 1.62f;
            const Vector3 normal{static_cast<float>(sx), 0.0f, 0.0f};
            const Vector3 a{x, y0, z0};
            const Vector3 b{x, y1, z0};
            const Vector3 c{x, y1, z1};
            const Vector3 d{x, y0, z1};

            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(214, 91, 47, 255);
                const Vector3 q[4] = {a, b, c, d};
                for (int i = 0; i < 4; ++i) {
                    rlVertex3f(q[i].x, q[i].y, q[i].z);
                    rlVertex3f(q[(i + 1) % 4].x, q[(i + 1) % 4].y, q[(i + 1) % 4].z);
                }
                rlEnd();
                return;
            }

            const bool flipU = sx < 0;
            const float u0 = flipU ? 1.0f : 0.0f;
            const float u1 = flipU ? 0.0f : 1.0f;
            rlSetTexture(g_sideDecal.id);
            rlBegin(RL_QUADS);
            rlColor4ub(255, 255, 255, 255);
            rlNormal3f(normal.x, normal.y, normal.z);
            if (sx > 0) {
                rlTexCoord2f(u0, 1.0f); rlVertex3f(a.x, a.y, a.z);
                rlTexCoord2f(u0, 0.0f); rlVertex3f(b.x, b.y, b.z);
                rlTexCoord2f(u1, 0.0f); rlVertex3f(c.x, c.y, c.z);
                rlTexCoord2f(u1, 1.0f); rlVertex3f(d.x, d.y, d.z);
            } else {
                rlTexCoord2f(u0, 1.0f); rlVertex3f(a.x, a.y, a.z);
                rlTexCoord2f(u1, 1.0f); rlVertex3f(d.x, d.y, d.z);
                rlTexCoord2f(u1, 0.0f); rlVertex3f(c.x, c.y, c.z);
                rlTexCoord2f(u0, 0.0f); rlVertex3f(b.x, b.y, b.z);
            }
            rlEnd();
            rlSetTexture(0);
        }

    } // namespace

    // ===== Public building blocks (declared in the header) =============================

    // Chassis: the whole baked glTF body (main bone + the two front sub-assemblies).
    void drawChassis(bool wire) {
        drawParts(BODY_PARTS, wire);
        drawParts(HUB_L_PARTS, wire);
        drawParts(HUB_R_PARTS, wire);
    }

    // One road wheel at the local origin, axle along X: tyre cylinder + two hubcap disks.
    void drawWheel(bool wire) {
        rlPushMatrix();
        rlRotatef(-90.0f, 0.0f, 0.0f, 1.0f);  // cylinder +Y axis -> +X
        drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, TIRE_RADIUS, TIRE_WIDTH, RUBBER_BLACK, wire, WHEEL_SIDES);
        drawCylinder(Vector3{0.0f, TIRE_WIDTH * 0.5f - 0.02f, 0.0f}, TIRE_RADIUS * 0.52f, 0.05f, HUBCAP_BLUE, wire,
                     WHEEL_SIDES);
        drawCylinder(Vector3{0.0f, -TIRE_WIDTH * 0.5f + 0.02f, 0.0f}, TIRE_RADIUS * 0.52f, 0.05f, HUBCAP_BLUE, wire,
                     WHEEL_SIDES);
        rlPopMatrix();
    }

    // One headlight at the local origin, axle along +Z (facing forward): cylinder + disk.
    void drawLight(bool wire) {
        rlPushMatrix();
        rlRotatef(90.0f, 1.0f, 0.0f, 0.0f);  // cylinder +Y axis -> +Z
        drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, LIGHT_RADIUS, LIGHT_DEPTH, LIGHT_YELLOW, wire, LIGHT_SIDES);
        rlPopMatrix();
    }

    void LoadCarResources() {
        ensureResourcesLoaded();
    }

    void UnloadCarResources() {
        if (!g_resourcesLoaded) {
            return;
        }
        if (g_sideDecal.id != 0) {
            UnloadTexture(g_sideDecal);
        }
        g_sideDecal = {};
        g_resourcesLoaded = false;
    }

    void drawCar(bool wire) {
        ensureResourcesLoaded();

        rlPushMatrix();
        {
            // Baked glTF body (filled boxes, real per-part transforms + materials).
            drawChassis(wire);

            // Round parts rebuilt as cylinders (assignment requirement).
            drawWheels(wire);
            drawHeadlights(wire);
            drawSpareWheel(wire);

            // The one textured feature: the flame side decal, left + right.
            for (int sx = -1; sx <= 1; sx += 2) {
                drawSideDecal(sx, wire);
            }
        }
        rlPopMatrix();
    }

} // namespace raylibgl::model
