#include "model/Scooby-van.hpp"

#include "model/Primitives.hpp"

#include <array>
#include <cmath>
#include <span>

#include <rlgl.h>

// =====================================================================================
//  Scooby-Doo "Mystery Machine" van.
//
//  GENERATED by `scooby-do-the-mystery-machine_zip/gen2.py` from the Blockbench glTF
//  (`source/scooby_do.gltf`). Re-run the generator to change the data tables (the only
//  baked data left is ROOFBAR_PARTS); do not hand-edit this file.
//
//  The whole body is ONE extruded-hull mesh (drawBodyShell): a side silhouette extruded
//  across the width, with two half-hexagon wheel-arch notches. Everything else sits on
//  top as its own helper: wheels, front emblem, windshield, doors, head/tail-lights,
//  bumpers, seats, mirrors, the roof aquarium + fish, and the flame side decal.
//
//  Materials are a flat palette: turquoise body, light-blue glass, yellow lights, grey
//  metal. Coordinates are in the centroid-recentred frame (glTF centroid (0,1.2365,0.089)
//  -> origin), Y up, front = -Z, so the trackball spins about the model centre.
// =====================================================================================

namespace raylibgl::model {

    namespace {

        // One baked Blockbench cuboid: centre + size, an axis-angle rotation (degrees),
        // and a flat material colour.
        struct Part {
            float center[3];
            float size[3];
            float axisAngle[4];  // {ax, ay, az, degrees}
            unsigned char color[4];
        };

        const Part ROOFBAR_PARTS[] = {
            {{0.0,1.198,-0.2869}, {2.0,0.125,0.125}, {1.0,0.0,0.0,0.0}, {175,185,196,255}},
            {{0.0,1.261,1.026}, {2.0,0.125,0.125}, {1.0,0.0,0.0,0.0}, {175,185,196,255}},
        };

        // ---- Round parts, measured from the glTF octagon clusters -----------------------
        constexpr float WHEEL_X = 0.80f;
        constexpr float WHEEL_Y = -0.91f;
        constexpr float FRONT_AXLE_Z = -0.95f;
        constexpr float REAR_AXLE_Z = 0.98f;
        constexpr float TIRE_RADIUS = 0.41f;
        constexpr float TIRE_WIDTH = 0.37f;
        constexpr int WHEEL_SIDES = 14;
        constexpr float HUB_RADIUS = 0.26f;  // yellow emblem disk on the tyre face

        // Front emblem: a yellow disk with three orange sticks crossing it, on the bumper.
        constexpr float LOGO_RADIUS = 0.40f;
        constexpr float LOGO_DEPTH = 0.10f;
        constexpr float LOGO_Y = -0.18f;
        constexpr float LOGO_Z = -1.98f;
        constexpr int LOGO_SIDES = 16;

        constexpr Color BODY_TURQUOISE = Color{28, 181, 186, 255};
        constexpr Color METAL_GREY = Color{175, 185, 196, 255};
        constexpr Color RUBBER_BLACK = Color{24, 29, 35, 255};
        constexpr Color LOGO_YELLOW = Color{247, 225, 111, 255};
        constexpr Color LOGO_ORANGE = Color{214, 91, 47, 255};
        constexpr Color GLASS_BLUE = Color{135, 206, 235, 255};
        constexpr Color SEATS_BROWN = Color{137, 81, 41, 255};

        // Two red rectangle tail-lights on the rear face, above the bumper.
        constexpr float TAIL_X = 0.66f;
        constexpr float TAIL_Y = -0.46f;
        constexpr float TAIL_Z = 2.02f;

        // Side decal plane, flush on the side wall (x=1.00) so it can't float or clip.
        constexpr float DECAL_X = 1.005f;

        Texture2D g_sideDecal{};
        Texture2D g_glow{};  // soft radial sprite, additively blended for the light bloom
        bool g_resourcesLoaded = false;

        void ensureResourcesLoaded() {
            if (g_resourcesLoaded) {
                return;
            }
            // The decal is loaded from assets/ (CMake copies the folder next to the exe);
            // the path is built from the application directory so the CWD doesn't matter.
            g_sideDecal = LoadTexture(TextFormat("%sassets/MysteryMachineSideDecal.png", GetApplicationDirectory()));
            SetTextureFilter(g_sideDecal, TEXTURE_FILTER_POINT);

            Image gi = GenImageGradientRadial(128, 128, 0.10f, Color{255, 255, 255, 255}, Color{255, 255, 255, 0});
            g_glow = LoadTextureFromImage(gi);
            SetTextureFilter(g_glow, TEXTURE_FILTER_BILINEAR);
            UnloadImage(gi);

            g_resourcesLoaded = true;
        }

        // Draw a baked group of cuboids, each with its own translate + rotate.
        void drawParts(std::span<const Part> parts, bool wire) {
            for (const Part& p : parts) {
                rlPushMatrix();
                rlTranslatef(p.center[0], p.center[1], p.center[2]);
                if (p.axisAngle[3] != 0.0f) {
                    rlRotatef(p.axisAngle[3], p.axisAngle[0], p.axisAngle[1], p.axisAngle[2]);
                }
                drawBox(Vector3{0.0f, 0.0f, 0.0f}, Vector3{p.size[0], p.size[1], p.size[2]},
                        Color{p.color[0], p.color[1], p.color[2], p.color[3]}, wire);
                rlPopMatrix();
            }
        }

        // ---- The body: one extruded-hull mesh -------------------------------------------
        struct ProfilePt {
            float z, y;
        };
        constexpr float ARCH_Y = -0.35f;       // wheel-arch ceiling
        constexpr float BODY_BOTTOM = -0.86f;  // body bottom
        constexpr float BODY_HALF_W = 0.99f;   // side-wall x

        // Outer silhouette, CW from front-bottom: front face + clip, roof, rear clip + face,
        // then the floor with the rear wheel arch and the mirrored front arch.
        constexpr std::array<ProfilePt, 14> BODY_OUTLINE = {{
            {-1.95f, BODY_BOTTOM}, {-1.95f, 0.24f}, {-1.55f, 1.18f},
            {1.55f, 1.18f}, {1.92f, 0.70f}, {1.95f, BODY_BOTTOM},
            {1.42f, BODY_BOTTOM}, {1.22f, ARCH_Y}, {0.75f, ARCH_Y}, {0.55f, BODY_BOTTOM},
            {-0.55f, BODY_BOTTOM}, {-0.75f, ARCH_Y}, {-1.22f, ARCH_Y}, {-1.42f, BODY_BOTTOM},
        }};

        // --- Front doors (both sides) ----------------------------------------------------
        // The door is a pentagon carved into the side: a front edge that follows the van
        // profile (raked down parallel to the windshield, then straight down at the emblem
        // height), a vertical rear edge, horizontal top + bottom. The window is the same
        // shape inset by a constant width, so the door panel is an equal-width frame.
        constexpr float DOOR_BOTTOM = -0.15f;  // leaves a body strip above the wheel arch
        constexpr ProfilePt D_FT{-1.35f, 0.95f};         // front-top
        constexpr ProfilePt D_FBend{-1.66f, 0.22f};      // front edge bends here (emblem height)
        constexpr ProfilePt D_FB{-1.66f, DOOR_BOTTOM};   // front-bottom (straight down from the bend)
        constexpr ProfilePt D_RT{-0.62f, 0.95f};         // rear-top
        constexpr ProfilePt D_RB{-0.62f, DOOR_BOTTOM};   // rear-bottom
        constexpr ProfilePt W_FB{-1.56f, 0.22f};         // window corners (front edge parallel to the door)
        constexpr ProfilePt W_FT{-1.288f, 0.86f};
        constexpr ProfilePt W_RT{-0.71f, 0.86f};
        constexpr ProfilePt W_RB{-0.71f, 0.22f};
        constexpr float DOOR_X = 0.91f;   // door panel plane (recessed in from the body)
        constexpr float GLASS_X = 0.85f;  // door glass plane (recessed in from the panel)

        // The upper side band, tiled as regions that fill it everywhere EXCEPT the door hole.
        // Each is fan-triangulated from its first vertex.
        constexpr std::array<ProfilePt, 7> BODY_FRONT_PILLAR = {{  // front face + rake + A-pillar
            {-1.95f, ARCH_Y}, {-1.95f, 0.24f}, {-1.55f, 1.18f}, {-1.35f, 1.18f},
            {-1.35f, 0.95f}, {-1.66f, 0.22f}, {-1.66f, ARCH_Y},
        }};
        constexpr std::array<ProfilePt, 4> BODY_DOOR_TOP = {{      // strip above the door
            {-1.35f, 0.95f}, {-1.35f, 1.18f}, {-0.62f, 1.18f}, {-0.62f, 0.95f},
        }};
        constexpr std::array<ProfilePt, 4> BODY_DOOR_BOTTOM = {{   // strip below the door
            {-1.66f, ARCH_Y}, {-1.66f, DOOR_BOTTOM}, {-0.62f, DOOR_BOTTOM}, {-0.62f, ARCH_Y},
        }};
        constexpr std::array<ProfilePt, 6> BODY_REAR_PANEL = {{    // the side behind the door
            {-0.62f, ARCH_Y}, {-0.62f, 0.95f}, {-0.62f, 1.18f},
            {1.55f, 1.18f}, {1.92f, 0.70f}, {1.95f, ARCH_Y},
        }};
        constexpr std::array<ProfilePt, 4> BODY_FRONT_LOWER = {{
            {-1.95f, BODY_BOTTOM}, {-1.95f, ARCH_Y}, {-1.22f, ARCH_Y}, {-1.42f, BODY_BOTTOM},
        }};
        constexpr std::array<ProfilePt, 4> BODY_SILL = {{
            {-0.55f, BODY_BOTTOM}, {-0.75f, ARCH_Y}, {0.75f, ARCH_Y}, {0.55f, BODY_BOTTOM},
        }};
        constexpr std::array<ProfilePt, 4> BODY_REAR_LOWER = {{
            {1.42f, BODY_BOTTOM}, {1.22f, ARCH_Y}, {1.95f, ARCH_Y}, {1.95f, BODY_BOTTOM},
        }};

        // Fan-triangulate one convex profile piece into both side walls (outward normals).
        void emitSideFan(std::span<const ProfilePt> p, float L, float R) {
            for (std::size_t i = 1; i + 1 < p.size(); ++i) {
                rlNormal3f(1.0f, 0.0f, 0.0f);  // right wall (+X)
                rlVertex3f(R, p[0].y, p[0].z); rlVertex3f(R, p[i].y, p[i].z); rlVertex3f(R, p[i + 1].y, p[i + 1].z);
                rlNormal3f(-1.0f, 0.0f, 0.0f);  // left wall (-X)
                rlVertex3f(L, p[0].y, p[0].z); rlVertex3f(L, p[i + 1].y, p[i + 1].z); rlVertex3f(L, p[i].y, p[i].z);
            }
        }

        void drawDoorFrame(int sx, bool wire);

        void drawBodyShell(bool wire) {
            const Color col = BODY_TURQUOISE;
            const float L = -BODY_HALF_W, R = BODY_HALF_W;

            drawBox(Vector3{0.0f, -0.78f, -1.96f}, Vector3{2.12f, 0.34f, 0.26f}, METAL_GREY, wire);  // front bumper
            drawBox(Vector3{0.0f, -0.78f, 1.96f}, Vector3{2.12f, 0.34f, 0.26f}, METAL_GREY, wire);   // rear bumper

            // Belly pan: one flat panel closing the open underbody between the four wheels.
            // The wheel-arch notches leave the bottom open down to ARCH_Y, so from below the
            // inner gap reads as hollow; this fills it. Spans inboard of the wheels (half-width
            // 0.615 = the tyre inner faces) and the full wheelbase; top tucked just under the
            // floor line (BODY_BOTTOM) so it doesn't z-fight the existing floor strips.
            drawBox(Vector3{0.0f, BODY_BOTTOM + 0.25f, 0.0f}, Vector3{1.03f, 0.51f, 2.84f}, col, wire);  // belly pan

            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(col.r, col.g, col.b, col.a);
                for (std::size_t i = 0; i < BODY_OUTLINE.size(); ++i) {
                    const ProfilePt& a = BODY_OUTLINE[i];
                    const ProfilePt& b = BODY_OUTLINE[(i + 1) % BODY_OUTLINE.size()];
                    rlVertex3f(L, a.y, a.z); rlVertex3f(L, b.y, b.z);
                    rlVertex3f(R, a.y, a.z); rlVertex3f(R, b.y, b.z);
                    rlVertex3f(L, a.y, a.z); rlVertex3f(R, a.y, a.z);
                }
                rlEnd();
                return;
            }

            // Disable culling for the hull only, so the cabin interior shows through the
            // semi-transparent windows. Culling applies per batch, so flush around the change.
            rlDrawRenderBatchActive();
            rlDisableBackfaceCulling();

            // Side walls: the upper band tiled around the door hole + the lower body pieces.
            rlBegin(RL_TRIANGLES);
            rlColor4ub(col.r, col.g, col.b, col.a);
            emitSideFan(BODY_FRONT_PILLAR, L, R);
            emitSideFan(BODY_DOOR_TOP, L, R);
            emitSideFan(BODY_DOOR_BOTTOM, L, R);
            emitSideFan(BODY_REAR_PANEL, L, R);
            emitSideFan(BODY_FRONT_LOWER, L, R);
            emitSideFan(BODY_SILL, L, R);
            emitSideFan(BODY_REAR_LOWER, L, R);
            rlEnd();

            // Swept outline edges = front/roof/rear/floor faces + the wheel-arch interiors.
            // Edge 1 (the front rake) is skipped: it is the windshield, drawn by drawWindshield.
            rlBegin(RL_QUADS);
            rlColor4ub(col.r, col.g, col.b, col.a);
            for (std::size_t i = 0; i < BODY_OUTLINE.size(); ++i) {
                if (i == 1) continue;
                const ProfilePt& a = BODY_OUTLINE[i];
                const ProfilePt& b = BODY_OUTLINE[(i + 1) % BODY_OUTLINE.size()];
                const float dz = b.z - a.z, dy = b.y - a.y;
                float ny, nz;
                if (dy == 0.0f && a.y == BODY_BOTTOM) {
                    ny = 1.0f; nz = 0.0f;  // flat floor strip: face up so it lights as a floor
                } else {
                    const float len = std::hypot(dz, dy);
                    ny = (len > 0.0f) ? dz / len : 0.0f;
                    nz = (len > 0.0f) ? -dy / len : 0.0f;
                }
                rlNormal3f(0.0f, ny, nz);
                rlVertex3f(L, a.y, a.z); rlVertex3f(L, b.y, b.z);
                rlVertex3f(R, b.y, b.z); rlVertex3f(R, a.y, a.z);
            }
            rlEnd();

            // Inset doors, drawn inside the culling-off block so the reveals read from any angle.
            drawDoorFrame(-1, wire);
            drawDoorFrame(1, wire);

            rlDrawRenderBatchActive();
            rlEnableBackfaceCulling();
        }

        // A general quad (filled or wire) with an explicit outward normal.
        void quad3(Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 nrm, Color col, bool wire) {
            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(col.r, col.g, col.b, col.a);
                const Vector3 q[4] = {a, b, c, d};
                for (int i = 0; i < 4; ++i) {
                    rlVertex3f(q[i].x, q[i].y, q[i].z);
                    rlVertex3f(q[(i + 1) % 4].x, q[(i + 1) % 4].y, q[(i + 1) % 4].z);
                }
                rlEnd();
                return;
            }
            rlBegin(RL_QUADS);
            rlColor4ub(col.r, col.g, col.b, col.a);
            rlNormal3f(nrm.x, nrm.y, nrm.z);
            rlVertex3f(a.x, a.y, a.z); rlVertex3f(b.x, b.y, b.z);
            rlVertex3f(c.x, c.y, c.z); rlVertex3f(d.x, d.y, d.z);
            rlEnd();
        }

        // One front door (sx = -1 left, +1 right): an equal-width frame panel recessed at
        // DOOR_X, with reveal walls closing the door recess (body -> panel) and the window
        // recess (panel -> glass). The glass itself is drawn by drawDoorGlass.
        void drawDoorFrame(int sx, bool wire) {
            const Color body = BODY_TURQUOISE;
            const float bx = sx * BODY_HALF_W;  // body side-wall plane
            const float dx = sx * DOOR_X;       // door panel plane
            const Vector3 nOut{static_cast<float>(sx), 0.0f, 0.0f};
            auto V = [](ProfilePt p, float x) { return Vector3{x, p.y, p.z}; };
            const ProfilePt SILL{-0.62f, 0.22f};  // door rear edge at the window-sill height

            // Door panel: a solid lower door + 3 equal-width frame strips around the window.
            quad3(V(D_FB, dx), V(D_RB, dx), V(SILL, dx), V(D_FBend, dx), nOut, body, wire);  // lower door
            quad3(V(D_FBend, dx), V(D_FT, dx), V(W_FT, dx), V(W_FB, dx), nOut, body, wire);  // front frame
            quad3(V(D_FT, dx), V(D_RT, dx), V(W_RT, dx), V(W_FT, dx), nOut, body, wire);     // top frame
            quad3(V(D_RT, dx), V(SILL, dx), V(W_RB, dx), V(W_RT, dx), nOut, body, wire);     // rear frame

            // Door recess reveals: body (bx) -> door panel (dx), around the pentagon edge.
            quad3(V(D_FT, bx), V(D_FBend, bx), V(D_FBend, dx), V(D_FT, dx), Vector3{0, 0, 1}, body, wire);  // front slant
            quad3(V(D_FBend, bx), V(D_FB, bx), V(D_FB, dx), V(D_FBend, dx), Vector3{0, 0, 1}, body, wire);  // front vertical
            quad3(V(D_FB, bx), V(D_RB, bx), V(D_RB, dx), V(D_FB, dx), Vector3{0, 1, 0}, body, wire);        // bottom
            quad3(V(D_RB, bx), V(D_RT, bx), V(D_RT, dx), V(D_RB, dx), Vector3{0, 0, -1}, body, wire);       // rear
            quad3(V(D_RT, bx), V(D_FT, bx), V(D_FT, dx), V(D_RT, dx), Vector3{0, -1, 0}, body, wire);       // top

            // Window recess reveals: door panel (dx) -> glass (gx), around the window edge.
            const float gx = sx * GLASS_X;
            quad3(V(W_FB, dx), V(W_FT, dx), V(W_FT, gx), V(W_FB, gx), Vector3{0, 0, 1}, body, wire);   // front
            quad3(V(W_FT, dx), V(W_RT, dx), V(W_RT, gx), V(W_FT, gx), Vector3{0, -1, 0}, body, wire);  // top
            quad3(V(W_RT, dx), V(W_RB, dx), V(W_RB, gx), V(W_RT, gx), Vector3{0, 0, -1}, body, wire);  // rear
            quad3(V(W_RB, dx), V(W_FB, dx), V(W_FB, gx), V(W_RB, gx), Vector3{0, 1, 0}, body, wire);   // bottom
        }

        // The front-door glass: a semi-transparent trapezoid recessed at GLASS_X (glass pass).
        void drawDoorGlass(int sx, bool wire) {
            const float gx = sx * GLASS_X;
            const Color glass = Color{GLASS_BLUE.r, GLASS_BLUE.g, GLASS_BLUE.b, 140};
            const Vector3 nOut{static_cast<float>(sx), 0.0f, 0.0f};
            auto V = [](ProfilePt p, float x) { return Vector3{x, p.y, p.z}; };
            quad3(V(W_FB, gx), V(W_FT, gx), V(W_RT, gx), V(W_RB, gx), nOut, glass, wire);
        }

        // Front bench seat in the cabin: a flat cushion box + a seat-back box tilted back,
        // reaching to just under the windshield base. Solid boxes, so it reads in wireframe.
        void drawSeats(bool wire) {
            const Color col = SEATS_BROWN;
            drawBox(Vector3{0.0f, -0.26f, -1.00f}, Vector3{1.5f, 0.14f, 0.72f}, col, wire);  // cushion
            rlPushMatrix();
            rlTranslatef(0.0f, -0.24f, -0.64f);   // pivot at the back of the cushion
            rlRotatef(13.0f, 1.0f, 0.0f, 0.0f);   // tilt the seat-back top backward
            drawBox(Vector3{0.0f, 0.52f, 0.0f}, Vector3{1.5f, 1.04f, 0.20f}, col, wire);     // seat back
            rlPopMatrix();
        }

        // One triangle with a computed outward face normal (call inside rlBegin(RL_TRIANGLES)).
        void emitTri(Vector3 a, Vector3 b, Vector3 c) {
            const float ux = b.x - a.x, uy = b.y - a.y, uz = b.z - a.z;
            const float vx = c.x - a.x, vy = c.y - a.y, vz = c.z - a.z;
            float nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
            const float len = std::hypot(nx, ny, nz);
            if (len > 0.0f) { nx /= len; ny /= len; nz /= len; }
            rlNormal3f(nx, ny, nz);
            rlVertex3f(a.x, a.y, a.z); rlVertex3f(b.x, b.y, b.z); rlVertex3f(c.x, c.y, c.z);
        }

        // UV sphere band from latitude latMin..latMax (full sphere = -PI/2..PI/2; a smaller
        // latMax leaves an open top = a bowl). Outward per-vertex normals; wire = lat/long cage.
        void drawSphere(Vector3 ctr, float r, float latMin, float latMax, int rings, int slices, Color col, bool wire) {
            auto dir = [](float lat, float lon) {
                return Vector3{std::cos(lat) * std::cos(lon), std::sin(lat), std::cos(lat) * std::sin(lon)};
            };
            auto put = [&](Vector3 d) { rlVertex3f(ctr.x + r * d.x, ctr.y + r * d.y, ctr.z + r * d.z); };
            auto lat = [&](int i) { return latMin + (latMax - latMin) * (float)i / rings; };
            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(col.r, col.g, col.b, col.a);
                for (int i = 0; i <= rings; ++i)
                    for (int j = 0; j < slices; ++j) { put(dir(lat(i), 2*PI*j/slices)); put(dir(lat(i), 2*PI*(j+1)/slices)); }
                for (int j = 0; j < slices; ++j)
                    for (int i = 0; i < rings; ++i) { put(dir(lat(i), 2*PI*j/slices)); put(dir(lat(i+1), 2*PI*j/slices)); }
                rlEnd();
                return;
            }
            rlBegin(RL_TRIANGLES);
            rlColor4ub(col.r, col.g, col.b, col.a);
            auto V = [&](Vector3 d) { rlNormal3f(d.x, d.y, d.z); put(d); };
            for (int i = 0; i < rings; ++i) {
                float la0 = lat(i), la1 = lat(i+1);
                for (int j = 0; j < slices; ++j) {
                    float lo0 = 2*PI*j/slices, lo1 = 2*PI*(j+1)/slices;
                    Vector3 a=dir(la0,lo0), b=dir(la1,lo0), c=dir(la1,lo1), d=dir(la0,lo1);
                    V(a); V(b); V(c);
                    V(a); V(c); V(d);
                }
            }
            rlEnd();
        }

        // Flat horizontal disk (normal +Y), used for the aquarium water surface.
        void drawDisk(Vector3 c, float r, int slices, Color col, bool wire) {
            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(col.r, col.g, col.b, col.a);
                for (int j = 0; j < slices; ++j) {
                    float a0 = 2*PI*j/slices, a1 = 2*PI*(j+1)/slices;
                    rlVertex3f(c.x+r*std::cos(a0), c.y, c.z+r*std::sin(a0));
                    rlVertex3f(c.x+r*std::cos(a1), c.y, c.z+r*std::sin(a1));
                }
                rlEnd();
                return;
            }
            rlBegin(RL_TRIANGLES);
            rlColor4ub(col.r, col.g, col.b, col.a);
            for (int j = 0; j < slices; ++j) {
                float a0 = 2*PI*j/slices, a1 = 2*PI*(j+1)/slices;
                rlNormal3f(0.0f, 1.0f, 0.0f);
                rlVertex3f(c.x, c.y, c.z);
                rlVertex3f(c.x+r*std::cos(a0), c.y, c.z+r*std::sin(a0));
                rlVertex3f(c.x+r*std::cos(a1), c.y, c.z+r*std::sin(a1));
            }
            rlEnd();
        }

        // Roof aquarium (a fishbowl) on the bench. Three layers sell "water in glass": an
        // inner water dome capped by a flat surface disk, inside a near-transparent glass
        // bowl cut open flat at the top. Drawn in the glass pass with depth-write + culling
        // off so the translucent layers blend cleanly.
        constexpr float AQ_RADIUS = 0.35f;
        // On the bench, right side: y rests on the cushion top, x>0 = right (flip for left).
        constexpr Vector3 AQ_CENTER{0.40f, -0.24f + AQ_RADIUS, -1.0f};
        void drawAquarium(bool wire) {
            const float R = AQ_RADIUS;
            const Color glass = Color{GLASS_BLUE.r, GLASS_BLUE.g, GLASS_BLUE.b, 42};
            const Color water = Color{74, 168, 196, 128};
            const Color surf  = Color{180, 224, 240, 150};
            const float bowlTop = 52.0f * DEG2RAD;    // glass cut open here (flat rim)
            const float waterLat = 16.0f * DEG2RAD;   // waterline
            const float wr = 0.9f * R * std::cos(waterLat);
            const float wy = AQ_CENTER.y + 0.9f * R * std::sin(waterLat);
            const Vector3 surfC{AQ_CENTER.x, wy, AQ_CENTER.z};
            const int rg = wire ? 8 : 12, sl = wire ? 14 : 18;
            if (!wire) { rlDrawRenderBatchActive(); rlDisableBackfaceCulling(); rlDisableDepthMask(); }
            drawSphere(AQ_CENTER, 0.9f*R, -PI*0.5f, waterLat, rg, sl, water, wire);  // water body
            drawDisk(surfC, wr, sl, surf, wire);                                     // water surface
            drawSphere(AQ_CENTER, R, -PI*0.5f, bowlTop, rg, sl, glass, wire);        // open glass bowl
            if (!wire) { rlDrawRenderBatchActive(); rlEnableDepthMask(); rlEnableBackfaceCulling(); }
        }

        // Orange goldfish inside the aquarium: a diamond cube body + a pyramid tail + 2 eyes.
        // Total length = half the aquarium radius; head points -Z.
        constexpr Color FISH_ORANGE{255, 130, 30, 255};
        constexpr float FISH_LENGTH = AQ_RADIUS * 0.5f;
        constexpr Vector3 FISH_CENTER{AQ_CENTER.x, AQ_CENTER.y - 0.05f, AQ_CENTER.z};
        void drawGoldfish(bool wire) {
            const float L = FISH_LENGTH;
            const Color o = FISH_ORANGE;
            rlPushMatrix();
            rlTranslatef(FISH_CENTER.x, FISH_CENTER.y, FISH_CENTER.z);
            // Body: a cube tilted 45 deg about its width axis so its side profile is a diamond.
            rlPushMatrix();
            rlTranslatef(0.0f, 0.0f, -0.182f*L);
            rlRotatef(45.0f, 1.0f, 0.0f, 0.0f);
            drawBox(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.45f*L, 0.45f*L, 0.45f*L}, o, wire);
            rlPopMatrix();
            // Tail: a flat triangular fin from the body's rear point out to a tall back edge.
            const Vector3 A{0.0f, 0.0f, 0.136f*L};
            const float w = 0.30f*L, h = 0.30f*L, zb = 0.42f*L;
            const Vector3 B0{-w,-h,zb}, B1{w,-h,zb}, B2{w,h,zb}, B3{-w,h,zb};
            if (wire) {
                rlBegin(RL_LINES); rlColor4ub(o.r,o.g,o.b,o.a);
                const Vector3 base[4] = {B0,B1,B2,B3};
                for (int i = 0; i < 4; ++i) {
                    rlVertex3f(A.x,A.y,A.z); rlVertex3f(base[i].x,base[i].y,base[i].z);
                    rlVertex3f(base[i].x,base[i].y,base[i].z);
                    rlVertex3f(base[(i+1)%4].x,base[(i+1)%4].y,base[(i+1)%4].z);
                }
                rlEnd();
            } else {
                rlBegin(RL_TRIANGLES); rlColor4ub(o.r,o.g,o.b,o.a);
                emitTri(A,B1,B0); emitTri(A,B2,B1); emitTri(A,B3,B2); emitTri(A,B0,B3);  // sides
                emitTri(B0,B1,B2); emitTri(B0,B2,B3);                                    // base fin
                rlEnd();
            }
            // Two small black eyes (short cylinders), drawn proud of the head so they sit on top.
            const Color eye = Color{15, 15, 18, 255};
            for (int sx = -1; sx <= 1; sx += 2) {
                rlPushMatrix();
                rlTranslatef(sx * 0.225f*L, 0.06f*L, -0.30f*L);
                rlRotatef(90.0f, 0.0f, 0.0f, 1.0f);  // cylinder axis +Y -> sideways (X)
                drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, 0.085f*L, 0.13f*L, eye, wire, 10);
                rlPopMatrix();
            }
            rlPopMatrix();
        }

        // Windshield: the body's raked front-top IS the frame (the hull edge skipped in
        // drawBodyShell). It is drawn as a body-colour border around an opening, with one
        // semi-transparent glass quad recessed inside it and reveal walls closing the depth.
        void drawWindshield(bool wire) {
            const Color body = BODY_TURQUOISE;
            const Color glass = Color{GLASS_BLUE.r, GLASS_BLUE.g, GLASS_BLUE.b, 140};
            const Vector3 N{0.0f, 0.391f, -0.920f};  // rake outward normal (front-up)
            // Point on the rake at along-rake fraction t (0=emblem top, 1=roof) and width x.
            auto P = [](float t, float x) {
                return Vector3{x, 0.24f + 0.94f * t, -1.95f + 0.40f * t};
            };
            const float W = BODY_HALF_W;          // frame outer half-width (meets the side walls)
            const float xw = 0.74f;               // window half-width
            const float tb = 0.10f, tt = 0.90f;   // window bottom / top along the rake
            const Vector3 r{0.0f, -0.0235f, 0.0552f};  // recess offset = -N * 0.06
            auto G = [&](float t, float x) { Vector3 p = P(t, x); return Vector3{p.x, p.y + r.y, p.z + r.z}; };

            // Frame border on the rake surface; wound BL,TL,TR,BR -> normal N.
            quad3(P(0, -W), P(tb, -W), P(tb, W), P(0, W), N, body, wire);          // bottom rail
            quad3(P(tt, -W), P(1, -W), P(1, W), P(tt, W), N, body, wire);          // top rail (roofline)
            quad3(P(tb, -W), P(tt, -W), P(tt, -xw), P(tb, -xw), N, body, wire);    // left pillar
            quad3(P(tb, xw), P(tt, xw), P(tt, W), P(tb, W), N, body, wire);        // right pillar

            // Reveal walls closing the gap between the frame opening and the recessed glass.
            quad3(P(tb, -xw), G(tb, -xw), G(tb, xw), P(tb, xw), Vector3{0.0f, 1.0f, 0.0f}, body, wire);   // bottom
            quad3(P(tt, xw), G(tt, xw), G(tt, -xw), P(tt, -xw), Vector3{0.0f, -1.0f, 0.0f}, body, wire);  // top
            quad3(P(tt, -xw), G(tt, -xw), G(tb, -xw), P(tb, -xw), Vector3{1.0f, 0.0f, 0.0f}, body, wire); // left
            quad3(P(tb, xw), G(tb, xw), G(tt, xw), P(tt, xw), Vector3{-1.0f, 0.0f, 0.0f}, body, wire);    // right

            // The glass, recessed along -N and rotated to the rake angle. Drawn last so it
            // blends over the reveals/body behind it.
            quad3(G(tb, -xw), G(tt, -xw), G(tt, xw), G(tb, xw), N, glass, wire);
        }

        // Headlights, above the bumper: a yellow lens recessed inside a proud grey frame.
        // Split so the housing is lit with the body while the lens is drawn emissive.
        void drawHeadlightHousings(bool wire) {
            for (int sx = -1; sx <= 1; sx += 2) {
                rlPushMatrix();
                rlTranslatef(sx * 0.66f, -0.46f, -1.95f);  // flanking the emblem
                drawBox(Vector3{0.0f, 0.13f, -0.05f}, Vector3{0.42f, 0.06f, 0.10f}, METAL_GREY, wire);   // top
                drawBox(Vector3{0.0f, -0.13f, -0.05f}, Vector3{0.42f, 0.06f, 0.10f}, METAL_GREY, wire);  // bottom
                drawBox(Vector3{-0.18f, 0.0f, -0.05f}, Vector3{0.06f, 0.32f, 0.10f}, METAL_GREY, wire);  // left
                drawBox(Vector3{0.18f, 0.0f, -0.05f}, Vector3{0.06f, 0.32f, 0.10f}, METAL_GREY, wire);   // right
                rlPopMatrix();
            }
        }
        // Hot lens core, drawn emissive by the caller (with an additive halo in drawCarGlow).
        void drawHeadlightLenses(bool wire) {
            for (int sx = -1; sx <= 1; sx += 2) {
                rlPushMatrix();
                rlTranslatef(sx * 0.66f, -0.46f, -1.95f);
                drawBox(Vector3{0.0f, 0.0f, -0.03f}, Vector3{0.30f, 0.20f, 0.04f}, Color{255, 247, 222, 255}, wire);
                rlPopMatrix();
            }
        }

        void drawRoofBars(bool wire) { drawParts(ROOFBAR_PARTS, wire); }  // the two grey roof cross-bars

        // Place the four road wheels with matrix transforms; geometry from drawWheel.
        void drawWheels(bool wire) {
            const float z[] = {FRONT_AXLE_Z, REAR_AXLE_Z};
            for (int sx = -1; sx <= 1; sx += 2) {
                for (float wz: z) {
                    rlPushMatrix();
                    rlTranslatef(sx * WHEEL_X, WHEEL_Y, wz);
                    drawWheel(wire);
                    rlPopMatrix();
                }
            }
        }

        // Two red rectangle tail-lights above the rear bumper (emissive core; halo added later).
        void drawTailLights(bool wire) {
            for (int sx = -1; sx <= 1; sx += 2) {
                rlPushMatrix();
                rlTranslatef(sx * TAIL_X, TAIL_Y, TAIL_Z);
                drawBox(Vector3{0.0f, 0.0f, 0.0f}, Vector3{0.34f, 0.26f, 0.14f}, Color{240, 56, 46, 255}, wire);
                rlPopMatrix();
            }
        }

        // One additive radial glow sprite on a Z-facing plane (culling is off, so winding
        // is irrelevant -- it just blooms outward).
        void drawGlowSprite(float x, float y, float z, float hw, float hh, Color col) {
            rlSetTexture(g_glow.id);
            rlBegin(RL_QUADS);
            rlColor4ub(col.r, col.g, col.b, col.a);
            rlNormal3f(0.0f, 0.0f, -1.0f);
            rlTexCoord2f(0.0f, 1.0f); rlVertex3f(x - hw, y - hh, z);
            rlTexCoord2f(1.0f, 1.0f); rlVertex3f(x + hw, y - hh, z);
            rlTexCoord2f(1.0f, 0.0f); rlVertex3f(x + hw, y + hh, z);
            rlTexCoord2f(0.0f, 0.0f); rlVertex3f(x - hw, y + hh, z);
            rlEnd();
            rlSetTexture(0);
        }

        // The shared "yellow disk + three orange crossing sticks" badge, in a canonical frame:
        // the disk axis is +Y and the sticks lie in the XZ plane (rotated about Y), proud by
        // `proud` along Y. Both the front emblem and each wheel hub orient it with a wrapping
        // matrix, so the badge is modelled once.
        void drawEmblem(float radius, float depth, int sides, float stickLenFactor,
                        float stickW, float stickH, float proud, bool wire) {
            drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, radius, depth, LOGO_YELLOW, wire, sides);
            for (int k = 0; k < 3; ++k) {
                rlPushMatrix();
                rlTranslatef(0.0f, proud, 0.0f);
                rlRotatef(60.0f * k, 0.0f, 1.0f, 0.0f);
                drawBox(Vector3{0.0f, 0.0f, 0.0f}, Vector3{2.0f * radius * stickLenFactor, stickW, stickH},
                        LOGO_ORANGE, wire);
                rlPopMatrix();
            }
        }

        // Front emblem on the bumper: the shared badge, rotated to face forward (-Z).
        void drawFrontLogo(bool wire) {
            rlPushMatrix();
            rlTranslatef(0.0f, LOGO_Y, LOGO_Z);
            rlRotatef(90.0f, 1.0f, 0.0f, 0.0f);  // canonical +Y disk axis -> faces along Z
            drawEmblem(LOGO_RADIUS, LOGO_DEPTH, LOGO_SIDES, 0.92f, 0.05f, 0.07f,
                       -(LOGO_DEPTH * 0.5f + 0.015f), wire);
            rlPopMatrix();
        }

        // Left/right flame decal: the only textured geometry, mirrored across the two sides.
        void drawSideDecal(int sx, bool wire) {
            const float x = sx * DECAL_X;
            const float y0 = -0.27f, y1 = 0.845f, z0 = -0.18f, z1 = 1.924f;
            const Vector3 a{x, y0, z0};
            const Vector3 b{x, y1, z0};
            const Vector3 c{x, y1, z1};
            const Vector3 d{x, y0, z1};

            if (wire) {
                rlBegin(RL_LINES);
                rlColor4ub(214, 91, 47, 255);
                const Vector3 q[4] = {a, b, c, d};
                for (int i = 0; i < 4; ++i) {
                    rlVertex3f(q[i].x, q[i].y, q[i].z);
                    rlVertex3f(q[(i + 1) % 4].x, q[(i + 1) % 4].y, q[(i + 1) % 4].z);
                }
                rlEnd();
                return;
            }

            // Flip U on the right side so the text reads correctly (not mirrored) on each side.
            const bool flipU = sx > 0;
            const float u0 = flipU ? 1.0f : 0.0f;
            const float u1 = flipU ? 0.0f : 1.0f;
            rlSetTexture(g_sideDecal.id);
            rlBegin(RL_QUADS);
            rlColor4ub(255, 255, 255, 255);
            rlNormal3f(static_cast<float>(sx), 0.0f, 0.0f);
            if (sx > 0) {
                rlTexCoord2f(u0, 1.0f); rlVertex3f(a.x, a.y, a.z);
                rlTexCoord2f(u0, 0.0f); rlVertex3f(b.x, b.y, b.z);
                rlTexCoord2f(u1, 0.0f); rlVertex3f(c.x, c.y, c.z);
                rlTexCoord2f(u1, 1.0f); rlVertex3f(d.x, d.y, d.z);
            } else {
                rlTexCoord2f(u0, 1.0f); rlVertex3f(a.x, a.y, a.z);
                rlTexCoord2f(u1, 1.0f); rlVertex3f(d.x, d.y, d.z);
                rlTexCoord2f(u1, 0.0f); rlVertex3f(c.x, c.y, c.z);
                rlTexCoord2f(u0, 0.0f); rlVertex3f(b.x, b.y, b.z);
            }
            rlEnd();
            rlSetTexture(0);
        }

        // Dark asphalt ground patch so the headlight spotlights cast a visible pool. Lit by
        // the scene + spotlights; the wheels rest on it.
        constexpr float GROUND_Y = WHEEL_Y - TIRE_RADIUS;
        void drawGround(bool wire) {
            const Color c = Color{46, 48, 56, 255};
            const float x0 = -3.2f, x1 = 3.2f, z0 = -4.8f, z1 = 3.0f, gy = GROUND_Y;
            quad3(Vector3{x0, gy, z0}, Vector3{x0, gy, z1}, Vector3{x1, gy, z1}, Vector3{x1, gy, z0},
                  Vector3{0.0f, 1.0f, 0.0f}, c, wire);
        }

        // Turquoise side mirrors on both sides: a short arm + an upright mirror head.
        void drawMirrors(bool wire) {
            const Color col = BODY_TURQUOISE;
            for (int sx = -1; sx <= 1; sx += 2) {
                const float s = static_cast<float>(sx);
                drawBox(Vector3{s * 1.06f, 0.66f, -1.55f}, Vector3{0.18f, 0.045f, 0.03f}, col, wire);  // arm
                drawBox(Vector3{s * 1.18f, 0.68f, -1.57f}, Vector3{0.25f, 0.35f, 0.05f}, col, wire);   // mirror head
            }
        }

    } // namespace

    // ===== Public building blocks (declared in the header) =============================

    // Chassis: the whole body as one extruded hull mesh (with grey bumpers) + roof bars.
    void drawChassis(bool wire) {
        drawBodyShell(wire);
        drawRoofBars(wire);
    }

    // One road wheel at the local origin, axle along X: a black tyre with the shared emblem
    // badge on each outer face.
    void drawWheel(bool wire) {
        rlPushMatrix();
        rlRotatef(-90.0f, 0.0f, 0.0f, 1.0f);  // cylinder +Y axis -> +X (axle); wheel plane = XZ
        drawCylinder(Vector3{0.0f, 0.0f, 0.0f}, TIRE_RADIUS, TIRE_WIDTH, RUBBER_BLACK, wire, WHEEL_SIDES);

        for (int s = -1; s <= 1; s += 2) {
            const float face = s * TIRE_WIDTH * 0.5f;
            rlPushMatrix();
            rlTranslatef(0.0f, face, 0.0f);
            drawEmblem(HUB_RADIUS, 0.06f, WHEEL_SIDES, 0.9f, 0.05f, 0.06f, s * 0.04f, wire);
            rlPopMatrix();
        }
        rlPopMatrix();
    }

    void LoadCarResources() {
        ensureResourcesLoaded();
    }

    void UnloadCarResources() {
        if (!g_resourcesLoaded) {
            return;
        }
        if (g_sideDecal.id != 0) {
            UnloadTexture(g_sideDecal);
        }
        if (g_glow.id != 0) {
            UnloadTexture(g_glow);
        }
        g_sideDecal = {};
        g_glow = {};
        g_resourcesLoaded = false;
    }

    // Opaque, lit parts: the hull + wheels + emblem + grey headlight housings + decals.
    void drawCarBody(bool wire) {
        ensureResourcesLoaded();
        drawGround(wire);
        drawChassis(wire);
        drawSeats(wire);
        drawMirrors(wire);
        drawGoldfish(wire);
        drawWheels(wire);
        drawFrontLogo(wire);
        drawHeadlightHousings(wire);
        for (int sx = -1; sx <= 1; sx += 2) {
            drawSideDecal(sx, wire);
        }
    }

    // Emissive light cores: the hot headlight lenses + red tail-lights. The caller draws
    // these with the shader's emission term so they read as glowing lamps.
    void drawCarLights(bool wire) {
        drawHeadlightLenses(wire);
        drawTailLights(wire);
    }

    // Additive bloom halos around each light -- a glow effect (not a surface material), so it
    // is drawn outside the lighting shader with additive blending + depth-write off.
    void drawCarGlow(bool wire) {
        if (wire || g_glow.id == 0) {
            return;
        }
        rlSetBlendMode(RL_BLEND_ADDITIVE);
        rlDisableBackfaceCulling();
        rlDisableDepthMask();
        const Color warm = Color{255, 236, 180, 255};
        const Color red = Color{255, 64, 48, 255};
        for (int sx = -1; sx <= 1; sx += 2) {
            drawGlowSprite(sx * 0.66f, -0.46f, -2.04f, 0.42f, 0.36f, warm);          // headlight halo
            drawGlowSprite(sx * 0.66f, -0.46f, -2.04f, 0.20f, 0.17f, warm);          // headlight hot core
            drawGlowSprite(sx * TAIL_X, TAIL_Y, TAIL_Z + 0.12f, 0.36f, 0.32f, red);  // tail-light halo
            drawGlowSprite(sx * TAIL_X, TAIL_Y, TAIL_Z + 0.12f, 0.18f, 0.15f, red);  // tail-light hot core
        }
        rlDrawRenderBatchActive();
        rlEnableDepthMask();
        rlEnableBackfaceCulling();
        rlSetBlendMode(RL_BLEND_ALPHA);
    }

    // Transparent parts. The aquarium is drawn first: it sits inside the cabin, so the
    // windows must blend OVER it (drawing it after would let their depth occlude it).
    void drawCarGlass(bool wire) {
        drawAquarium(wire);
        drawWindshield(wire);
        if (wire) {
            drawDoorGlass(-1, wire);
            drawDoorGlass(1, wire);
            return;
        }
        // Side door glass: draw double-sided so it reads from inside and out regardless of winding.
        rlDrawRenderBatchActive();
        rlDisableBackfaceCulling();
        drawDoorGlass(-1, wire);
        drawDoorGlass(1, wire);
        rlDrawRenderBatchActive();
        rlEnableBackfaceCulling();
    }

    void drawCar(bool wire) {
        ensureResourcesLoaded();
        rlPushMatrix();
        {
            drawCarBody(wire);
            drawCarLights(wire);
            drawCarGlass(wire);
            drawCarGlow(wire);
        }
        rlPopMatrix();
    }

} // namespace raylibgl::model
